steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/evaan-gke-buildtrigger:v1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/evaan-gke-buildtrigger:v1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-config
  - --image=gcr.io/${PROJECT_ID}/evaan-gke-buildtrigger:v1
  - --location=us-central1-c
  - --cluster=tinu-cluster-1
  - --expose=8080
  