apiVersion: v1
kind: Service
metadata:
  annotations:
  name: demo-app
spec:
  selector:
    app: demo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-app
  namespace: "default"
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app  
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers: 
      - name: demo-app
        image: gcr.io/evaan-332713/evaan-gke-buildtrigger:v1
        ports:
        - containerPort: 5001     