apiVersion: v1
kind: Service
metadata:
  annotations:
  name: sabertooth
spec:
  selector:
    app: sabertooth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sabertooth
  namespace: "default"
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabertooth  
  template:
    metadata:
      labels:
        app: sabertooth
    spec:
      containers: 
      - name: demo-app
        image: gcr.io/evaan-332713/evaan-gke-buildtrigger:v1
        ports:
        - containerPort: 8081    